### ISSUE TITLE
Crash & hang on big repos

### ISSUE THREAD

**Issue by iguanacucumber** [isakbm/gitgraph.nvim#1] opened 2024-08-03 22:03 UTC
on the rust repo, it crashes:
```
E5108: Error executing lua: ...er/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:461: attempt to 
index local 'next_commit' (a nil value)                                                                 
stack traceback:                                                                                        
        ...er/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:461: in function 'get_is_bi_crossing
'                                                                                                       
        ...er/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:711: in function 'straight_j'       
        ...er/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:838: in function 'gitgraph'         
        ...er/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:2029: in function 'draw'            
        /home/user/.config/nvim/init.lua:486: in function </home/user/.config/nvim/init.lua:485>        
Press ENTER or type command to continue
```
and on the linux kernel repo, it just hangs and locks neovim entirely

**Comment by isakbm** [comment] 2024-08-03 22:10
Thanks for opening the first issue!

Could you provide links to the repositories that the plugin is struggling with?

**Comment by isakbm** [comment] 2024-08-04 08:06
I just ran in on the rust repo, and I had no issues other than that it took a good 5 seconds to complete.

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/8e27fdb4-afc3-4f03-b406-0113981b51d4">

It is slow but it works.

Performance is something that I will be improving asap of course :)

Could you link the repo that is causing the crash for you?

**Comment by iguanacucumber** [comment] 2024-08-04 09:35
https://github.com/rust-lang/rust -> crash the plugin
https://github.com/torvalds/linux -> crash neovim / softlock
Is there any log i can provide ?

**Comment by isakbm** [comment] 2024-08-04 09:49
The most helpful would be for me to try to reproduce the error on my side. The crash in the rust repo is not something I am able to reproduce at the moment.

What arguments / options are you passing to "gitgraph.nvim" draw ?

**Comment by iguanacucumber** [comment] 2024-08-04 10:05
i orriginaly tried with this:
require('gitgraph').draw({}, { all = true, max_count = 5000 })
then i tried with or without some arguments, but it still crash every time i do a require

**Comment by isakbm** [comment] 2024-08-04 10:26
Can you try with max_count = 10?

**Comment by isakbm** [comment] 2024-08-04 10:32
For now can you try with max_count = 100, just out of curiosity. This seems to at least on my end to not trigger the bug. Hoping that you have the same behaviour on your end. That is, I hope that if you set max_count=100, that it works.

Of course that is not a solution, just a curiosity that will give me an idea of how severe this bug is or not.

**Comment by iguanacucumber** [comment] 2024-08-04 11:52
same error

**Comment by iguanacucumber** [comment] 2024-08-04 12:39
i tried the plugin again, on macos this time and it works on the rust repo ( it just takes 2 whole minutes, and uses 2G of RAM but it works )

**Comment by isakbm** [comment] 2024-08-04 13:42
Thanks for this added information.

The memory usage is expected to be high as literally the entire history is loaded into memory in lua tables.

Pagination (buffering) etc will be one of the first optimisations I carry out. Hopefully it will reduce memory consumption and speed up the rendering / loading :)

**Comment by isakbm** [comment] 2024-08-04 20:17
Most likely found the cause of the crash.

Will aim for a patch within 24 hours. 🤞

Performance optimisation will be an ongoing project that will most likely take another couple of weeks though.

**Comment by isakbm** [comment] 2024-08-10 10:54
@iguanacucumber 

The crash should now hopefully be fixed.

Performance is still an issue of course, but will eventually be worked on, will therefore close this issue, and open a new one that is purely focused on performance.

**Closed** 2024-08-10 10:54 UTC

**Comment by iguanacucumber** [comment] 2024-08-10 13:52
it works 🥳
